name: Upload NPM package

on:
    release:
        types: published

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x
                  registry-url: 'https://registry.npmjs.org'

            - name: yarn install
              run: yarn install

            - name: yarn test
              run: yarn test

            - name: yarn lint
              run: yarn lint

            - name: yarn build
              run: yarn build

            - name: Set version
              run: |
                  echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
              env:
                  TAG_NAME: ${{github.event.release.tag_name}}

            - name: Update version
              run: yarn version --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --allow-same-version

            - name: Publish package
              run: yarn publish --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build TypeDocs
              run: npx typedoc src

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: docs
                CLEAN: true
                FOLDER: docs
                TARGET_FOLDER: /
