name: Run Lint and Tests

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        run: yarn test

      - name: yarn lint
        run: yarn lint


